### PR TITLE
Fix the NaN bug reported in issue 21

### LINKED ISSUE #21: Fix CLI bug: NaN error found. NaN error already in baseline.
After the latest change, when running `tsc-baseline check` the CLI outputs `NaN error found. NaN error already in baseline.` at the end of each run.

Screen Shot 2024-06-04 at 1 54 54 PM

Here's a demo repo for seeing the issue: https://github.com/wdoug/tsc-baseline-demo

I dug into this a little bit and realized it is a bug with the compilation. This code:
```ts
export const getTotalErrorsCount = (errorMap: Map<string, ErrorInfo>): number =>
  [...errorMap.values()].reduce((sum, info) => sum + info.count, 0)
```
Is being compiled (in the output `dist/cli.module.js` file) into:
```js
p=function(e){return[].concat(e.values()).reduce(function(e,r){return e+r.count}
```
This is wrong. It seems like it is assuming the call to `values()` on the errorMap is returning an array, but actually that returns an iterator.

For example:
```js
const m = new Map();
const result = [].concat(m.values())
// result is: [MapIterator]
```

Hopefully just updating whatever library is doing the compilation here should fix this.

### PR DESCRIPTION
**Pull request by BrianBasor**
This fixes #21 .

I really don't know why the compiler wanted to convert the TypeScript code the wrong way, but using `Array.from` instead of the spread operator and the array initializer seemed to work properly in my tests.

While I was at it, I fixed up the pluralization logic, but if that's getting off topic, I can yank that commit.

What do you think?

### CODE REVIEW

File: src/cli.ts [hunk 1]
```diff
@@ -69,15 +69,13 @@ import { rmSync } from 'fs'
         const oldErrorsCount = getTotalErrorsCount(oldErrors)
 
         const newErrorsCountMessage =
-          newErrorsCount === 0
-            ? '0 errors found'
-            : `${newErrorsCount} error${newErrorsCount > 1 ? 's' : ''} found`
+          `${newErrorsCount} error${newErrorsCount == 1 ? '' : 's'} found`
```
Comment (wdoug) [inline src/cli.ts:72]: Nice. Haha, I also was working on this and made almost the same change. 😅 

I think it might be nice to have it say "X _new_ errors found" to make it a little more clear:
```suggestion
          `${newErrorsCount} new error${newErrorsCount == 1 ? '' : 's'} found`
```

File: src/util.ts [hunk 2]
```diff
@@ -88,7 +88,7 @@ export const getNewErrors = (
 }
 
 export const getTotalErrorsCount = (errorMap: Map<string, ErrorInfo>): number =>
-  [...errorMap.values()].reduce((sum, info) => sum + info.count, 0)
+  Array.from(errorMap.values()).reduce((sum, info) => sum + info.count, 0)
```
Comment (wdoug) [inline src/util.ts:91]: What do you think about adding a comment of caution here for now. Maybe something like:
```suggestion
  // NOTE: Previously, this was written with an array spread, but there was a bug
  // with microbundle that was incorrectly compiling that (see: https://github.com/TimMikeladze/tsc-baseline/issues/21).
  // Until that is resolved or the bundler is switched for this repo, this has been
  // rewritten with Array.from
  Array.from(errorMap.values()).reduce((sum, info) => sum + info.count, 0)
```

**Comment by BrianBasor** [comment]
Thanks for the helpful suggestions @wdoug !

**Comment by wdoug** [comment]
@TimMikeladze, any chance we could move to get this merged/get this bug fixed soon?

**Comment by TimMikeladze** [comment]
I’ll merge all the PRs in the next 24hrs or so. I’m flying internationally
so have been a bit busy to sit down and review.

I appreciate the contributions!

Tim Mikeladze

**Comment by TimMikeladze** [comment]
Published as `1.4.0`. Thanks guys!

**Comment by wdoug** [comment]
I didn't mean to rush you while you were traveling! Anyway, thanks for getting this merged and published, @TimMikeladze!

**Comment by BrianBasor** [comment]
I hope your travels went smoothly.  Thanks for the review and merge @TimMikeladze !
